from kivy.uix.gridlayout import GridLayout
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.screenmanager import Screen
from kivy.uix.button import Button
from kivy.uix.label import Label
from kivy.uix.textinput import TextInput
from kivy.uix.scrollview import ScrollView

class players4(Screen):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        bl = BoxLayout(size_hint_y=None, height= 300)
        gl = GridLayout(cols= 4 , spacing=(15 , 5) , padding= (60 , 1 , 1 , 1))
        gl2 = GridLayout(cols=5, rows=29, spacing=(15 , 5), padding= 1, size_hint_y=None, height= 950)
        bl2 = BoxLayout(size_hint_y=None, height= 200)
        main_bl = BoxLayout(size_hint=(1, None), height=1600)
        
        bl.add_widget(Label(text= "Название команды" , color = "#02034e" , size_hint_y=None, height= 32 , font_size =28))
        self.name_team = TextInput(hint_text= "Приморкий край" , multiline=False, size_hint_y=None, height= 32)
        bl.add_widget(self.name_team)
        
        bl.add_widget(Label(text= "Название игры" , color = "#02034e", size_hint_y=None, height= 32 , font_size =24 ))
        self.name_match = TextInput(hint_text= "Первенство России среди кого и какого возраста", multiline=False, size_hint_y=None, height= 32)
        bl.add_widget(self.name_match)
        
        bl.add_widget(Label(text= "дата игры" , color = "#02034e", size_hint_y=None, height= 32 , font_size =24 ))
        self.date_match = TextInput(hint_text= "дд.мм.гггг", multiline=False, size_hint_y=None, height= 32)
        bl.add_widget(self.date_match)
        
        gl.add_widget(Label(text= "Имя и Фамилия" , color = "#02034e", size_hint_y=None, height= 32 , font_size =19 ))
        gl.add_widget(Label(text= "Имя и Фамилия" , color = "#02034e", size_hint_y=None, height= 32 , font_size =19 ))
        gl.add_widget(Label(text= "Имя и Фамилия" , color = "#02034e", size_hint_y=None, height= 32 , font_size =19 ))
        gl.add_widget(Label(text= "Имя и Фамилия" , color = "#02034e", size_hint_y=None, height= 32 , font_size =19 ))
        self.name_1 = TextInput(hint_text= "Имя и Фамилия", size_hint_y=None, height= 32)
        gl.add_widget(self.name_1)
        self.name_2 = TextInput(hint_text= "Имя и Фамилия", size_hint_y=None, height= 32)
        gl.add_widget(self.name_2)
        self.name_3 = TextInput(hint_text= "Имя и Фамилия", size_hint_y=None, height= 32)
        gl.add_widget(self.name_3)
        self.name_4 = TextInput(hint_text= "Имя и Фамилия", size_hint_y=None, height= 32)
        gl.add_widget(self.name_4)
        
        gl2.add_widget(Label(text="1" , color = "#02034e", size_hint=(None, 1) , size = (44 , 10) , font_size =18 ))
        self.one_1 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.one_1)
        self.one_2 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.one_2)
        self.one_3 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.one_3)
        self.one_4 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.one_4)
        
        gl2.add_widget(Label(text="2" , color = "#02034e", size_hint=(None, 1) , size = (44 , 10) , font_size =18 ))
        self.two_1 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.two_1)
        self.two_2 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.two_2)
        self.two_3 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.two_3)
        self.two_4 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.two_4)
        
        gl2.add_widget(Label(text="3" , color = "#02034e", size_hint=(None, 1) , size = (44 , 10) , font_size =18 ))
        self.three_1 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.three_1)
        self.three_2 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.three_2)
        self.three_3 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.three_3)
        self.three_4 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.three_4)
        
        gl2.add_widget(Label(text="4" , color = "#02034e", size_hint=(None, 1) , size = (44 , 10) , font_size =18 ))
        self.four_1 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.four_1)
        self.four_2 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.four_2)
        self.four_3 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.four_3)
        self.four_4 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.four_4)
        
        gl2.add_widget(Label(text="5" , color = "#02034e", size_hint=(None, 1) , size = (44 , 10) , font_size =18 ))
        self.five_1 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.five_1)
        self.five_2 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.five_2)
        self.five_3 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.five_3)
        self.five_4 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.five_4)
        
        gl2.add_widget(Label(text="6" , color = "#02034e", size_hint=(None, 1) , size = (44 , 10) , font_size =18 ))
        self.six_1 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.six_1)
        self.six_2 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.six_2)
        self.six_3 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.six_3)
        self.six_4 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.six_4)
        
        gl2.add_widget(Label(text="7" , color = "#02034e", size_hint=(None, 1) , size = (44 , 10) , font_size =18 ))
        self.seven_1 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.seven_1)
        self.seven_2 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.seven_2)
        self.seven_3 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.seven_3)
        self.seven_4 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.seven_4)
        
        gl2.add_widget(Label(text="8" , color = "#02034e", size_hint=(None, 1) , size = (44 , 10) , font_size =18 ))
        self.eight_1 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.eight_1)
        self.eight_2 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.eight_2)
        self.eight_3 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.eight_3)
        self.eight_4 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.eight_4)
        
        gl2.add_widget(Label(text="9" , color = "#02034e", size_hint=(None, 1) , size = (44 , 10) , font_size =18 ))
        self.nine_1 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.nine_1)
        self.nine_2 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.nine_2)
        self.nine_3 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.nine_3)
        self.nine_4 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.nine_4)
        
        gl2.add_widget(Label(text="10" , color = "#02034e", size_hint=(None, 1) , size = (44 , 10) , font_size =18 ))
        self.one_zero_1 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.one_zero_1)
        self.one_zero_2 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.one_zero_2)
        self.one_zero_3 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.one_zero_3)
        self.one_zero_4 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.one_zero_4)
        
        gl2.add_widget(Label(text="11" , color = "#02034e", size_hint=(None, 1) , size = (44 , 10) , font_size =18 ))
        self.one_one_1 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.one_one_1)
        self.one_one_2 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.one_one_2)
        self.one_one_3 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.one_one_3)
        self.one_one_4 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.one_one_4)
        
        gl2.add_widget(Label(text="12" , color = "#02034e", size_hint=(None, 1) , size = (44 , 10) , font_size =18 ))
        self.one_two_1 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.one_two_1)
        self.one_two_2 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.one_two_2)
        self.one_two_3 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.one_two_3)
        self.one_two_4 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.one_two_4)
        
        gl2.add_widget(Label(text="13" , color = "#02034e", size_hint=(None, 1) , size = (44 , 10) , font_size =18 ))
        self.one_three_1 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.one_three_1)
        self.one_three_2 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.one_three_2)
        self.one_three_3 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.one_three_3)
        self.one_three_4 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.one_three_4)
        
        gl2.add_widget(Label(text="14" , color = "#02034e", size_hint=(None, 1) , size = (44 , 10) , font_size =18 ))
        self.one_four_1 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.one_four_1)
        self.one_four_2 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.one_four_2)
        self.one_four_3 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.one_four_3)
        self.one_four_4 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.one_four_4)
        
        gl2.add_widget(Label(text="15" , color = "#02034e", size_hint=(None, 1) , size = (44 , 10) , font_size =18 ))
        self.one_five_1 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.one_five_1)
        self.one_five_2 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.one_five_2)
        self.one_five_3 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.one_five_3)
        self.one_five_4 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.one_five_4)
        
        gl2.add_widget(Label(text="16" , color = "#02034e", size_hint=(None, 1) , size = (44 , 10) , font_size =18 ))
        self.one_six_1 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.one_six_1)
        self.one_six_2 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.one_six_2)
        self.one_six_3 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.one_six_3)
        self.one_six_4 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.one_six_4)
        
        gl2.add_widget(Label(text="17" , color = "#02034e", size_hint=(None, 1) , size = (44 , 10) , font_size =18 ))
        self.one_seven_1 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.one_seven_1)
        self.one_seven_2 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.one_seven_2)
        self.one_seven_3 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.one_seven_3)
        self.one_seven_4 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.one_seven_4)
        
        gl2.add_widget(Label(text="18" , color = "#02034e", size_hint=(None, 1) , size = (44 , 10) , font_size =18 ))
        self.one_eight_1 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.one_eight_1)
        self.one_eight_2 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.one_eight_2)
        self.one_eight_3 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.one_eight_3)
        self.one_eight_4 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.one_eight_4)
        
        gl2.add_widget(Label(text="19" , color = "#02034e", size_hint=(None, 1) , size = (44 , 10) , font_size =18 ))
        self.one_nine_1 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.one_nine_1)
        self.one_nine_2 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.one_nine_2)
        self.one_nine_3 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.one_nine_3)
        self.one_nine_4 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.one_nine_4)
        
        gl2.add_widget(Label(text="20" , color = "#02034e", size_hint=(None, 1) , size = (44 , 10) , font_size =18 ))
        self.two_zero_1 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.two_zero_1)
        self.two_zero_2 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.two_zero_2)
        self.two_zero_3 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.two_zero_3)
        self.two_zero_4 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.two_zero_4)

        gl2.add_widget(Label(text="extra-1" , color = "#02034e", size_hint=(None, 1) , size = (44 , 10) , font_size =18 ))
        self.extra_one_1 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.extra_one_1)
        self.extra_one_2 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.extra_one_2)
        self.extra_one_3 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.extra_one_3)
        self.extra_one_4 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.extra_one_4)
        
        gl2.add_widget(Label(text="extra-2" , color = "#02034e", size_hint=(None, 1) , size = (44 , 10) , font_size =18 ))
        self.extra_two_1 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.extra_two_1)
        self.extra_two_2 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.extra_two_2)
        self.extra_two_3 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.extra_two_3)
        self.extra_two_4 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.extra_two_4)
        
        gl2.add_widget(Label(text="extra-3" , color = "#02034e", size_hint=(None, 1) , size = (44 , 10) , font_size =18 ))
        self.extra_three_1 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.extra_three_1)
        self.extra_three_2 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.extra_three_2)
        self.extra_three_3 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.extra_three_3)
        self.extra_three_4 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.extra_three_4)
        
        gl2.add_widget(Label(text="extra-4" , color = "#02034e", size_hint=(None, 1) , size = (44 , 10) , font_size =18 ))
        self.extra_four_1 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.extra_four_1)
        self.extra_four_2 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.extra_four_2)
        self.extra_four_3 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.extra_four_3)
        self.extra_four_4 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.extra_four_4)
        
        gl2.add_widget(Label(text="extra-5" , color = "#02034e", size_hint=(None, 1) , size = (44 , 10) , font_size =18 ))
        self.extra_five_1 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.extra_five_1)
        self.extra_five_2 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.extra_five_2)
        self.extra_five_3 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.extra_five_3)
        self.extra_five_4 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.extra_five_4)
        
        gl2.add_widget(Label(text="extra-6" , color = "#02034e", size_hint=(None, 1) , size = (44 , 10) , font_size =18 ))
        self.extra_six_1 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.extra_six_1)
        self.extra_six_2 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.extra_six_2)
        self.extra_six_3 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.extra_six_3)
        self.extra_six_4 = TextInput(hint_text= "0/1/2")
        gl2.add_widget(self.extra_six_4)
        
        end = Button(text= "Рассчёт")
        end.bind(on_release=self.math_operation)
        bl2.add_widget(end)
        
        match_plus = Button(text= "Назад")
        match_plus.bind(on_release=self.switch_match_plus)
        bl2.add_widget(match_plus)
        
        main_bl.add_widget(bl)
        main_bl.add_widget(gl)
        main_bl.add_widget(gl2)
        main_bl.add_widget(bl2)
        
        scroll = ScrollView()
        scroll.add_widget(main_bl)
        
        self.add_widget(scroll)
    
    def switch_match_plus(self, *args):
        self.manager.current = "Игра+"

    def math_operation(self, *args):
        pass